language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28

cache:
  directories:
  - .autoconf
  - $HOME/.m2

script:
- ./gradlew clean assembleDebug test lint

deploy:
  provider: script
  script: ./gradlew clean assembleRelease generatePomFileForFirestorePublication bintrayUpload
  skip_cleanup: false
  dry-run: false
  on:
    tags: true
